language: python
python:
    - "3.5.3"
install:
    - pip install -r requirements.txt
sudo: enable
script: 
    - python3 yuxe.py --help
before_install:
    - sudo add-apt-repository -y ppa:mc3man/trusty-media
    - sudo apt-get -qq update
    - sudo apt-get dist-upgrade
    - sudo apt-get install -y ffmpeg
